name: Webchart Authentication Workflow

on:
  push:
    branches:
      - master # Trigger the workflow on push to the main branch

jobs:
  authenticate_with_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use Node.js version 14
      
    - name: Install dependencies
      run: npm install # Install project dependencies
    
    - name: Authenticate with Cookiejar
      env:
        password: ${{ secrets.PASSWORD }}
        username: ${{ vars.USERNAME }}
      run: node Cookiejar.js $username

    - name: Authenticate with Bearertoken
      env:
        password: ${{ secrets.PASSWORD }}
        username: ${{ vars.USERNAME }}
      run: node Bearertoken.js $username $password
         
